// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtTYh1pklmsn2AVqlPesjhbUpVYkdU8Ac',
    appId: '1:1075803226220:web:78e31667d2eef66b315849',
    messagingSenderId: '1075803226220',
    projectId: 'tutguide-8bac9',
    authDomain: 'tutguide-8bac9.firebaseapp.com',
    storageBucket: 'tutguide-8bac9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD935RtufissHzaw_SCdLRvfVRXrUAwSm8',
    appId: '1:1075803226220:android:dbbcbe8ed6b05fb3315849',
    messagingSenderId: '1075803226220',
    projectId: 'tutguide-8bac9',
    storageBucket: 'tutguide-8bac9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjLgMgzTQeeH5QDkzGncpiYqwqwbUUxUU',
    appId: '1:1075803226220:ios:25f2db086563b50b315849',
    messagingSenderId: '1075803226220',
    projectId: 'tutguide-8bac9',
    storageBucket: 'tutguide-8bac9.appspot.com',
    iosClientId: '1075803226220-7ks2gnc4335o0ekfa6sium7vi4bqi2pi.apps.googleusercontent.com',
    iosBundleId: 'com.example.tutguide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjLgMgzTQeeH5QDkzGncpiYqwqwbUUxUU',
    appId: '1:1075803226220:ios:25f2db086563b50b315849',
    messagingSenderId: '1075803226220',
    projectId: 'tutguide-8bac9',
    storageBucket: 'tutguide-8bac9.appspot.com',
    iosClientId: '1075803226220-7ks2gnc4335o0ekfa6sium7vi4bqi2pi.apps.googleusercontent.com',
    iosBundleId: 'com.example.tutguide',
  );
}
